### ISSUE TITLE
Typo & incorrect data returned for admin user with SSH & Screensharing access

### ISSUE THREAD

**Issue by apizz** [tuxudo/users#2]
Looking at code, starting from line 89, there is a misspelling: listed as `group_memership` instead of `group_membership`.  

Additionally, an admin user on a Mac with both SSH & Remote Management enabled, is returning in this module as not having SSH or Screen Sharing access when in fact running `id` as the user reveals they part of the both the com.apple.access_screensharing and com.apple.access_ssh groups.  So something in the logic here isn't working as expected.

Module returns only being a member of 'Administrators, App Server Admins, Application Server, Print Administrators'.

**Comment by tuxudo** [comment]
The misspelling of `group_membership` is a bug that will likely not be fixed. This stems from it being the name of the database column as well and renaming columns is a tricky thing. I should have caught this error when initially creating the module, but didn't. Overall it has minimal, if any, end user impact. 

Group memberships are now obtained through processing with `id` command. Should resolve missing group memberships. Fixed in v1.2 of module

**Comment by apizz** [comment]
Hmm, so how does this get merged into the main repo's module?

**Comment by tuxudo** [comment]
Already merged in with commit https://github.com/tuxudo/users/commit/0b0f3d042416fb0f9574dc61c1a37e55ea84fad3 

Forgot to make a PR and merge :P

**Comment by tuxudo** [comment]
Merged into proper repo. Previously merged into tuxudo/ instead of munkireport/
